[mypy]
python_version = 3.11
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true

[mypy-httpx.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-playwright.*]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-server]
disallow_untyped_decorators = False