#!/usr/bin/env python3
"""Render domain-dependent Kubernetes and Ansible manifests from lab config.

Reads ``config/lab-domains.yaml`` and ``config/sso-policy.yaml``, applies
``LAB_*`` environment overrides, and writes generated Traefik routes, Authelia
and oauth2-proxy manifests, cert-manager resources, Ansible Helm values, and
Grafana dashboards under the repository ``generated/`` trees.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any, cast

try:
    import yaml
except ImportError:
    yaml = None

GENERATED_HEADER = "# Generated by render-domains.sh — do not edit.\n"


def repo_root() -> Path:
    """Resolve the repository root directory.

    Returns:
        Absolute path to the workspace root, taken from ``REPO_ROOT`` when set,
        otherwise inferred from this file's location.
    """
    return Path(os.environ.get("REPO_ROOT", Path(__file__).resolve().parents[2]))


def load_yaml(path: Path) -> dict[str, Any]:
    """Load a YAML or JSON configuration file into a dictionary.

    Args:
        path: Path to a ``.yaml``, ``.yml``, or ``.json`` config file.

    Returns:
        Parsed mapping from the file, or an empty dict when the document is
        empty or not a mapping.

    Raises:
        RuntimeError: If PyYAML is unavailable and the file is not JSON.
    """
    if yaml is None:
        if path.suffix == ".json":
            return cast(dict[str, Any], json.loads(path.read_text()))
        raise RuntimeError("PyYAML required to load YAML config")
    data = yaml.safe_load(path.read_text()) or {}
    return data if isinstance(data, dict) else {}


def apply_env(cfg: dict[str, Any]) -> dict[str, Any]:
    """Merge environment-variable overrides into a domain configuration.

    Args:
        cfg: Base domain configuration loaded from ``lab-domains.yaml``.

    Returns:
        Deep-copied configuration with ``LAB_*`` environment overrides applied
        and ``primary`` normalized to a valid apex domain.
    """
    out: dict[str, Any] = json.loads(json.dumps(cfg))
    out["local_domain"] = os.environ.get(
        "LAB_LOCAL_DOMAIN",
        os.environ.get("LAB_SSO_DOMAIN", out.get("local_domain", "lab.local")),
    )
    out["public_domain"] = os.environ.get("LAB_PUBLIC_DOMAIN", out.get("public_domain", "") or "")
    out["primary"] = os.environ.get("LAB_DOMAIN_PROFILE", os.environ.get("LAB_PRIMARY_DOMAIN", out.get("primary", "local")))
    out["email_domain"] = os.environ.get("LAB_EMAIL_DOMAIN", out.get("email_domain", out["local_domain"]))
    sso = out.setdefault("sso", {})
    sso["https_port"] = int(os.environ.get("LAB_SSO_HTTPS_PORT", sso.get("https_port", 32443)))
    sso["http_port"] = int(os.environ.get("LAB_SSO_HTTP_PORT", sso.get("http_port", 32080)))
    tls = out.setdefault("tls", {})
    if os.environ.get("LAB_ACME_EMAIL"):
        tls["acme_email"] = os.environ["LAB_ACME_EMAIL"]
    if out["primary"] not in ("local", "public"):
        out["primary"] = "local"
    if out["primary"] == "public" and not out["public_domain"]:
        out["primary"] = "local"
    return out


def fqdn(host: str, apex: str) -> str:
    """Build a fully qualified host name under an apex domain.

    Args:
        host: Service or subdomain label (for example ``grafana``).
        apex: Apex domain (for example ``lab.local``).

    Returns:
        Fully qualified domain name ``{host}.{apex}``.
    """
    return f"{host}.{apex}"


def host_match(host: str, local: str, public: str) -> str:
    """Build a Traefik ``Host()`` rule matching local and optional public FQDNs.

    Args:
        host: Service host label used in the route.
        local: Local apex domain.
        public: Public apex domain, or an empty string when unset.

    Returns:
        Traefik router match expression joined with `` || ``.
    """
    parts = [f"Host(`{fqdn(host, local)}`)"]
    if public:
        parts.append(f"Host(`{fqdn(host, public)}`)")
    return " || ".join(parts)


def service_url(host: str, apex: str, port: int, *, public_apex: bool) -> str:
    """Build an HTTPS service URL for dashboard or SSO links.

    Args:
        host: Service host label.
        apex: Apex domain for the URL.
        port: HTTPS port appended for non-public apex URLs.
        public_apex: When ``True``, omit the port (standard HTTPS).

    Returns:
        HTTPS URL ending with a trailing slash.
    """
    if public_apex:
        return f"https://{fqdn(host, apex)}/"
    return f"https://{fqdn(host, apex)}:{port}/"


def dump_yaml(doc: Any) -> str:
    """Serialize a Python object to a YAML manifest string.

    Multi-line strings use YAML literal block style (``|``) so generated
    ConfigMaps stay readable instead of single-line escaped blobs.

    Args:
        doc: Mapping or other structure to render as YAML.

    Returns:
        YAML text suitable for writing to a generated manifest file.

    Raises:
        RuntimeError: If PyYAML is not installed.
    """
    if yaml is None:
        raise RuntimeError("PyYAML required to render YAML manifests")

    class _Dumper(yaml.SafeDumper):
        """Local dumper with multi-line string literal style."""

    def _str_presenter(dumper: Any, data: str) -> Any:
        if "\n" in data:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

    _Dumper.add_representer(str, _str_presenter)
    return str(
        yaml.dump(
            doc,
            Dumper=_Dumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
    )


def write_text(path: Path, content: str) -> None:
    """Write generated manifest text, prepending the standard header when needed.

    Args:
        path: Destination file path; parent directories are created as needed.
        content: Manifest body to write.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.startswith("#"):
        content = GENERATED_HEADER + content
    path.write_text(content)


def sync_lab_domains_json(cfg: dict[str, Any], root: Path) -> None:
    """Write the resolved domain configuration to ``config/lab-domains.json``.

    Args:
        cfg: Domain configuration after environment overrides.
        root: Repository root path.
    """
    json_path = root / "config" / "lab-domains.json"
    json_path.write_text(json.dumps(cfg, indent=2) + "\n")


def render_routes(domains: dict[str, Any], sso_policy: dict[str, Any], root: Path) -> None:
    """Render Traefik IngressRoute manifests from SSO policy and domain config.

    Args:
        domains: Resolved lab domain configuration.
        sso_policy: SSO route definitions from ``sso-policy.yaml``.
        root: Repository root for output under ``k8s/auth/generated/``.
    """
    local = domains["local_domain"]
    public = domains["public_domain"]
    routes_cfg = sso_policy.get("routes") or []
    docs: list[str] = []

    for route in routes_cfg:
        host = route["host"]
        ns = route["namespace"]
        service = route["service"]
        port = route.get("port", 80)
        middlewares = route.get("middlewares") or []
        is_internal = route.get("internal", False)
        name = host.replace("@", "-").replace(".", "-")
        if host == "traefik":
            name = "traefik-dashboard"

        mw_refs = []
        for mw in middlewares:
            mw_refs.append(f"        - name: {mw}\n          namespace: auth")

        if is_internal:
            svc_block = """      services:
        - name: api@internal
          kind: TraefikService"""
        else:
            svc_block = f"""      services:
        - name: {service}
          port: {port}"""

        for apex, secret, suffix in _route_tls_variants(local, public):
            match = host_match(host, apex if suffix == "local" else local, public if suffix == "public" and public else "")
            if suffix == "local":
                match = f"Host(`{fqdn(host, local)}`)"
            elif suffix == "public" and public:
                match = f"Host(`{fqdn(host, public)}`)"
            else:
                continue

            route_name = name if suffix == "local" or not public else f"{name}-public"
            doc = f"""apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {route_name}
  namespace: {ns}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {match}
      kind: Rule
"""
            if mw_refs:
                doc += "      middlewares:\n" + "\n".join(mw_refs) + "\n"
            doc += svc_block + "\n"
            doc += f"""  tls:
    secretName: {secret}
"""
            docs.append(doc)

    # Headlamp ServersTransport (static helper)
    docs.append("""apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: headlamp-transport
  namespace: monitoring
spec:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 60s
    idleConnTimeout: 90s
""")

    # HTTP redirect routes
    local_esc = local.replace(".", "\\.")
    redirect_local = f"HostRegexp(`^.+\\\\.{local_esc}$`) || Host(`{local}`)"
    docs.append(f"""apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: {redirect_local}
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: auth
      services:
        - name: noop@internal
          kind: TraefikService
""")
    if public:
        public_esc = public.replace(".", "\\.")
        redirect_public = f"HostRegexp(`^.+\\\\.{public_esc}$`) || Host(`{public}`)"
        docs.append(f"""apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-public
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: {redirect_public}
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: auth
      services:
        - name: noop@internal
          kind: TraefikService
""")

    write_text(root / "k8s/auth/generated/routes.yaml", "---\n".join(docs))


def _route_tls_variants(local: str, public: str) -> list[tuple[str, str, str]]:
    """List TLS certificate variants to emit for each route.

    Args:
        local: Local apex domain.
        public: Public apex domain, or an empty string when unset.

    Returns:
        Tuples of ``(apex, secret_name, suffix)`` for each IngressRoute TLS
        block to generate.
    """
    items = [(local, "lab-wildcard-tls", "local")]
    if public:
        items.append((public, "lab-public-wildcard-tls", "public"))
    return items


def render_authelia_configmap(domains: dict[str, Any], root: Path) -> None:
    """Render the Authelia ConfigMap with domain-aware access and session rules.

    Args:
        domains: Resolved lab domain configuration.
        root: Repository root for output under ``k8s/auth/generated/``.
    """
    local = domains["local_domain"]
    public = domains["public_domain"]
    port = domains["sso"]["https_port"]
    primary = domains["primary"]
    apex = public if primary == "public" and public else local

    rules = [
        f'        - domain: "{fqdn("auth", local)}"\n          policy: bypass',
        f'        - domain: "{fqdn("oauth", local)}"\n          policy: bypass',
        f'        - domain: "*.{local}"\n          policy: one_factor',
    ]
    if public:
        rules.extend(
            [
                f'        - domain: "{fqdn("auth", public)}"\n          policy: bypass',
                f'        - domain: "{fqdn("oauth", public)}"\n          policy: bypass',
                f'        - domain: "*.{public}"\n          policy: one_factor',
            ]
        )

    cookies = [
        f"""        - domain: {local}
          authelia_url: https://{fqdn("auth", local)}
          default_redirection_url: https://{fqdn("dashboard", local)}"""
    ]
    if public:
        cookies.append(
            f"""        - domain: {public}
          authelia_url: https://{fqdn("auth", public)}
          default_redirection_url: https://{fqdn("dashboard", public)}"""
        )

    config_yml = f"""theme: dark
server:
  address: 'tcp://0.0.0.0:9091'
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth
log:
  level: info
totp:
  issuer: spark-{apex}
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2
      iterations: 3
      key_length: 32
      salt_length: 16
      memory: 65536
      parallelism: 4
access_control:
  default_policy: deny
  rules:
{chr(10).join(rules)}
session:
  name: authelia_session
  expiration: 12h
  inactivity: 45m
  cookies:
{chr(10).join(cookies)}
  redis:
    host: authelia-redis.auth.svc.cluster.local
    port: 6379
storage:
  local:
    path: /config/db.sqlite3
notifier:
  filesystem:
    filename: /config/notification.txt
# OIDC provider keys and clients are injected from authelia-secrets (see scripts/lib/sso.sh).
"""

    # Language-native Authelia config (lintable); ConfigMap embeds via literal |.
    config_path = root / "k8s/auth/generated/configuration.yml"
    write_text(config_path, config_yml if config_yml.endswith("\n") else config_yml + "\n")

    doc = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": "authelia-config", "namespace": "auth"},
        "data": {
            "configuration.yml": config_yml if config_yml.endswith("\n") else config_yml + "\n"
        },
    }
    write_text(root / "k8s/auth/generated/authelia-configmap.yaml", dump_yaml(doc))


def render_oauth2_proxy(domains: dict[str, Any], root: Path) -> None:
    """Render the oauth2-proxy Deployment manifest with OIDC and cookie domains.

    Args:
        domains: Resolved lab domain configuration.
        root: Repository root for output under ``k8s/auth/generated/``.
    """
    local = domains["local_domain"]
    public = domains["public_domain"]
    primary = domains["primary"]
    apex = public if primary == "public" and public else local

    cookie_domains = [f".{local}"]
    whitelist = [f".{local}"]
    if public:
        cookie_domains.append(f".{public}")
        whitelist.append(f".{public}")

    args = [
        "--provider=oidc",
        f"--oidc-issuer-url=https://{fqdn('auth', apex)}",
        "--client-id=oauth2-proxy",
        "--client-secret-file=/secrets/oauth2-proxy-client-secret",
        "--cookie-secret-file=/secrets/cookie-secret",
        "--email-domain=*",
        "--http-address=0.0.0.0:4180",
        f"--redirect-url=https://{fqdn('oauth', apex)}/oauth2/callback",
        "--reverse-proxy=true",
        "--upstream=static://202",
        "--cookie-secure=true",
        "--cookie-samesite=lax",
    ]
    for cd in cookie_domains:
        args.append(f"--cookie-domain={cd}")
    for wl in whitelist:
        args.append(f"--whitelist-domain={wl}")
    args.append("--skip-provider-button=true")

    args_block = "\n".join(f"            - {a}" for a in args)
    content = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: auth
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      priorityClassName: lab-management
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.2
          args:
{args_block}
          ports:
            - containerPort: 4180
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets
          projected:
            sources:
              - secret:
                  name: oauth2-proxy-secrets
                  items:
                    - key: cookie-secret
                      path: cookie-secret
              - secret:
                  name: sso-oidc-clients
                  items:
                    - key: oauth2-proxy-client-secret
                      path: oauth2-proxy-client-secret
"""
    write_text(root / "k8s/auth/generated/oauth2-proxy-deployment.yaml", content)


def render_certificates(domains: dict[str, Any], root: Path) -> None:
    """Render cert-manager Certificate and optional ACME ClusterIssuer manifests.

    Args:
        domains: Resolved lab domain configuration.
        root: Repository root for output under ``k8s/cert-manager/generated/``.
    """
    local = domains["local_domain"]
    public = domains["public_domain"]
    tls = domains.get("tls") or {}

    local_cert = {
        "apiVersion": "cert-manager.io/v1",
        "kind": "Certificate",
        "metadata": {"name": "lab-wildcard-tls", "namespace": "traefik"},
        "spec": {
            "secretName": "lab-wildcard-tls",
            "issuerRef": {"name": tls.get("local_issuer", "lab-ca-issuer"), "kind": "ClusterIssuer"},
            "dnsNames": [local, f"*.{local}"],
        },
    }
    write_text(
        root / "k8s/cert-manager/generated/wildcard-certificate.yaml",
        dump_yaml(local_cert),
    )

    cert_dir = root / "k8s/cert-manager/generated"
    acme_path = cert_dir / "cluster-issuer-acme.yaml"
    public_cert_path = cert_dir / "public-wildcard-certificate.yaml"
    if public:
        acme_email = tls.get("acme_email") or ""
        issuer_name = tls.get("public_issuer", "letsencrypt-prod")
        solver = tls.get("acme_solver", "http01")
        if solver == "http01":
            solvers = [
                {
                    "http01": {
                        "ingress": {"class": "traefik"},
                    }
                }
            ]
        else:
            solvers = [{"http01": {"ingress": {"class": "traefik"}}}]

        acme_doc = {
            "apiVersion": "cert-manager.io/v1",
            "kind": "ClusterIssuer",
            "metadata": {"name": issuer_name},
            "spec": {
                "acme": {
                    "server": "https://acme-v02.api.letsencrypt.org/directory",
                    "email": acme_email or "ops@example.com",
                    "privateKeySecretRef": {"name": f"{issuer_name}-account-key"},
                    "solvers": solvers,
                }
            },
        }
        write_text(acme_path, dump_yaml(acme_doc))

        public_cert = {
            "apiVersion": "cert-manager.io/v1",
            "kind": "Certificate",
            "metadata": {"name": "lab-public-wildcard-tls", "namespace": "traefik"},
            "spec": {
                "secretName": "lab-public-wildcard-tls",
                "issuerRef": {"name": issuer_name, "kind": "ClusterIssuer"},
                "dnsNames": [public, f"*.{public}"],
            },
        }
        write_text(public_cert_path, dump_yaml(public_cert))
    else:
        for path in (acme_path, public_cert_path):
            if path.exists():
                path.unlink()


def render_ansible_values(domains: dict[str, Any], root: Path) -> None:
    """Render Helm values files for Grafana and Coder under ``ansible/files/generated/``.

    Args:
        domains: Resolved lab domain configuration.
        root: Repository root path.
    """
    local = domains["local_domain"]
    public = domains["public_domain"]
    primary = domains["primary"]
    apex = public if primary == "public" and public else local

    grafana_host = fqdn("grafana", apex)
    grafana = f"""# Generated by render-domains.sh — do not edit.
service:
  type: ClusterIP

grafana.ini:
  server:
    root_url: "https://{grafana_host}/"
    domain: "{grafana_host}"
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: false
  dashboards:
    default_home_dashboard_path: /var/lib/grafana/dashboards/spark-lab/00-lab-overview.json

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 2Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true
        editable: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: spark-lab
        orgId: 1
        folder: DGX Spark Lab
        type: file
        disableDeletion: true
        editable: false
        options:
          path: /var/lib/grafana/dashboards/spark-lab

extraConfigmapMounts:
  - name: spark-lab-dashboards
    configMap: grafana-dashboards-spark-lab
    mountPath: /var/lib/grafana/dashboards/spark-lab
    readOnly: true
    subPath: ""
"""
    out = root / "ansible/files/generated"
    out.mkdir(parents=True, exist_ok=True)
    (out / "grafana-values.yaml").write_text(grafana)

    coder_uris = []
    for apex_name in ([local] + ([public] if public else [])):
        coder_uris.append(f'      value: "https://{fqdn("coder", apex_name)}"')
    auth_uris = [f'https://{fqdn("auth", a)}' for a in ([local] + ([public] if public else []))]

    coder = f"""# Generated by render-domains.sh — do not edit.
coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_ACCESS_URL
      value: "https://{fqdn("coder", apex)}"
    - name: CODER_OIDC_ISSUER_URL
      value: "https://{fqdn("auth", apex)}"
    - name: CODER_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: sso-oidc-clients
          key: coder-client-id
          optional: true
    - name: CODER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: sso-oidc-clients
          key: coder-client-secret
          optional: true
    - name: CODER_OIDC_SCOPES
      value: "openid,profile,email,offline_access"
    - name: CODER_DISABLE_PASSWORD_AUTH
      value: "true"
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

postgresql:
  enabled: true
  auth:
    username: coder
    password: coder
    database: coder
  primary:
    persistence:
      size: 10Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
"""
    (out / "coder-values.yaml").write_text(coder)


def render_grafana_dashboards(domains: dict[str, Any], root: Path) -> None:
    """Invoke the Grafana dashboard generator when the script is present.

    Args:
        domains: Resolved lab domain configuration (passed via env to the child).
        root: Repository root containing ``config/grafana/generate-dashboards.py``.

    Raises:
        subprocess.CalledProcessError: If the dashboard generator exits non-zero.
    """
    gen = root / "config" / "grafana" / "generate-dashboards.py"
    if not gen.exists():
        return
    import subprocess

    env = os.environ.copy()
    env["LAB_DOMAINS_CONFIG"] = str(root / "config" / "lab-domains.yaml")
    subprocess.run([sys.executable, str(gen)], check=True, cwd=root, env=env)


def render_cert_manager_kustomization(domains: dict[str, Any], root: Path) -> None:
    """Write ``k8s/cert-manager/kustomization.yaml`` listing generated cert resources.

    Args:
        domains: Resolved lab domain configuration (public certs when configured).
        root: Repository root path.
    """
    resources = ["cluster-issuer.yaml", "generated/wildcard-certificate.yaml"]
    if domains.get("public_domain"):
        resources.extend(
            [
                "generated/cluster-issuer-acme.yaml",
                "generated/public-wildcard-certificate.yaml",
            ]
        )
    lines = [
        "# Purpose: Kustomize bundle for cert-manager issuers and generated certificates",
        "# Source of truth: generated by render_domains.py from config/lab-domains.yaml",
        "# Regenerate: bazelisk run //scripts:run-utility -- render-domains",
        "# Safety: TLS material only; no cluster credentials",
        "",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "",
        "resources:",
        *[f"  - {r}" for r in resources],
        "",
    ]
    (root / "k8s/cert-manager/kustomization.yaml").write_text("\n".join(lines))


def main() -> int:
    """Load domain config and render all domain-dependent generated manifests.

    Returns:
        ``0`` on success.
    """
    root = repo_root()
    domains_path = root / "config" / "lab-domains.yaml"
    sso_path = root / "config" / "sso-policy.yaml"
    domains = apply_env(load_yaml(domains_path))
    sso_policy = load_yaml(sso_path)

    sync_lab_domains_json(domains, root)
    render_routes(domains, sso_policy, root)
    render_authelia_configmap(domains, root)
    render_oauth2_proxy(domains, root)
    render_certificates(domains, root)
    render_cert_manager_kustomization(domains, root)
    render_ansible_values(domains, root)
    render_grafana_dashboards(domains, root)
    print(f"render-domains: ok (local={domains['local_domain']} public={domains['public_domain'] or '<none>'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())