#!/usr/bin/env python3
"""Validator and renderer for the declarative lab topology (ansible/inventory/lab.yaml).

Invoked by shell as: ``python3 scripts/lib/py/lab_topology.py <command> [args...]``.

Commands:
    validate <lab.yaml>           print errors/warnings; exit 0 when valid.
    facts <lab.yaml>              print ``key=value`` lines (fabric, orchestrator, ...).
    wizard-vars <lab.yaml>        print ``key=value`` defaults for the setup wizard
                                  (current values a wizard should pre-fill).
    render <lab.yaml> [--out R]   write generated Ansible artifacts under ``R/ansible``:
                                  inventory/hosts.ini,
                                  inventory/group_vars/generated/fabric.yml,
                                  files/generated/netplan/<node>-99-highspeed.yaml,
                                  files/generated/cloud-init/user-data-<node>.yaml.

Exit codes: 0 ok, 1 validation/render error, 2 usage error.
"""
from __future__ import annotations

import argparse
import ipaddress
import re
import sys
from pathlib import Path

FABRICS = ("none", "pair", "ring", "switch")
# fabric -> (min_nodes, max_nodes). Switch is the CRS804 fabric: 4 full ports,
# or 5 with one breakout. The documented 3-node fabric is the QSFP ring.
FABRIC_NODE_RANGE = {"none": (1, 1), "pair": (2, 2), "ring": (3, 3), "switch": (4, 5)}
MAX_NODES = 5
NODE_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{0,62}$")
USER_NAME_RE = re.compile(r"^[a-z_][a-z0-9_-]{0,31}$")
DEFAULT_ANSIBLE_USER = "lab-ansible"
DEFAULT_BOOTSTRAP_USER = "ubuntu"
HS_IF_DEFAULT = ("enp1s0f0np0", "enp1s0f1np1")
GENERATED_BANNER = (
    "# Generated by scripts/lib/py/lab_topology.py from ansible/inventory/lab.yaml.",
    "# Do not edit — regenerate with ./scripts/manage.sh setup (or topology render).",
)


def _fail(messages: list[str]) -> int:
    for message in messages:
        print(f"lab-topology: {message}", file=sys.stderr)
    return 1


def load_lab(path: Path) -> dict:
    """Load the lab block from a topology YAML file; exit 2 on unreadable input."""
    try:
        import yaml
    except ImportError:
        print("lab-topology: PyYAML is required (python3-yaml / pip install pyyaml)", file=sys.stderr)
        return {}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception as exc:  # noqa: BLE001 - report any parse failure uniformly
        print(f"lab-topology: cannot parse {path}: {exc}", file=sys.stderr)
        return {}
    lab = data.get("lab")
    if not isinstance(lab, dict):
        print(f"lab-topology: {path} must contain a top-level `lab` mapping", file=sys.stderr)
        return {}
    return lab


def validate_lab(lab: dict) -> tuple[list[str], list[str]]:
    """Validate the lab mapping; return (errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []

    management = lab.get("management") or {}
    subnet = str(management.get("subnet", ""))
    try:
        network = ipaddress.ip_network(subnet)
    except ValueError:
        network = None
        errors.append(f"management.subnet must be an IPv4 CIDR (got {subnet!r})")
    ansible_user = lab.get("ansible_user")
    if not isinstance(ansible_user, str) or not ansible_user:
        lab["ansible_user"] = DEFAULT_ANSIBLE_USER
        ansible_user = DEFAULT_ANSIBLE_USER
    elif not USER_NAME_RE.match(ansible_user):
        errors.append(f"ansible_user must be a unix login name (got {ansible_user!r})")
    bootstrap_user = lab.get("bootstrap_user")
    if not isinstance(bootstrap_user, str) or not bootstrap_user:
        lab["bootstrap_user"] = DEFAULT_BOOTSTRAP_USER
        bootstrap_user = DEFAULT_BOOTSTRAP_USER
    elif not USER_NAME_RE.match(bootstrap_user):
        errors.append(f"bootstrap_user must be a unix login name (got {bootstrap_user!r})")

    fabric = lab.get("fabric")
    if fabric not in FABRICS:
        errors.append(f"fabric must be one of {list(FABRICS)} (got {fabric!r})")
        return errors, warnings

    nodes = lab.get("nodes")
    if not isinstance(nodes, list) or not nodes:
        errors.append("nodes must be a non-empty list")
        return errors, warnings
    if len(nodes) > MAX_NODES:
        errors.append(f"at most {MAX_NODES} nodes are supported (got {len(nodes)})")
    min_nodes, max_nodes = FABRIC_NODE_RANGE[fabric]
    if len(nodes) < min_nodes or len(nodes) > max_nodes:
        errors.append(
            f"fabric {fabric!r} supports {min_nodes}"
            + (f"–{max_nodes}" if max_nodes > min_nodes else "")
            + f" node(s), got {len(nodes)}"
        )
    seen_names: set[str] = set()
    seen_ips: set[str] = set()
    orchestrators = 0
    for idx, node in enumerate(nodes):
        label = f"nodes[{idx}]"
        if not isinstance(node, dict):
            errors.append(f"{label} must be a mapping")
            continue
        name = str(node.get("name", ""))
        if not NODE_NAME_RE.match(name):
            errors.append(f"{label}.name must be kebab-case (got {name!r})")
        if name in seen_names:
            errors.append(f"{label}.name is duplicated: {name!r}")
        seen_names.add(name)
        ip = str(node.get("ip", ""))
        try:
            address = ipaddress.ip_address(ip)
        except ValueError:
            address = None
            errors.append(f"{label}.ip must be an IPv4 address (got {ip!r})")
        if ip in seen_ips:
            errors.append(f"{label}.ip is duplicated: {ip!r}")
        seen_ips.add(ip)
        if address is not None and network is not None and address not in network:
            errors.append(f"{label}.ip {ip} is outside management.subnet {subnet}")
        role = node.get("role")
        if role is not None and role != "orchestrator":
            errors.append(f"{label}.role must be 'orchestrator' or omitted (got {role!r})")
        if role == "orchestrator":
            orchestrators += 1
        hs_ifs = node.get("hs_ifs")
        if hs_ifs is not None:
            if not isinstance(hs_ifs, list) or not all(isinstance(i, str) and i for i in hs_ifs):
                errors.append(f"{label}.hs_ifs must be a list of interface names")
            elif len(hs_ifs) > 2 or len(set(hs_ifs)) != len(hs_ifs):
                errors.append(f"{label}.hs_ifs must name at most 2 distinct interfaces")

    if orchestrators == 0:
        errors.append("exactly one node must carry role: orchestrator (found none)")
    elif orchestrators > 1:
        errors.append(f"exactly one node must carry role: orchestrator (found {orchestrators})")

    if fabric != "none":
        for idx, node in enumerate(nodes):
            if not isinstance(node, dict) or not node.get("hs_ifs"):
                errors.append(f"nodes[{idx}].hs_ifs is required for fabric {fabric!r}")

    switch = lab.get("switch")
    if fabric == "switch":
        if not isinstance(switch, dict):
            errors.append("fabric switch requires a switch block (host, user, port_map)")
        else:
            brand = str(switch.get("brand", ""))
            if brand != "mikrotik":
                errors.append(f"switch.brand must be 'mikrotik' (got {brand!r})")
            if not str(switch.get("model", "")):
                errors.append("switch.model is required")
            host = str(switch.get("host", ""))
            try:
                host_addr = ipaddress.ip_address(host)
            except ValueError:
                host_addr = None
                errors.append(f"switch.host must be an IPv4 address (got {host!r})")
            if host_addr is not None and network is not None and host_addr not in network:
                errors.append(f"switch.host {host} is outside management.subnet {subnet}")
            user = str(switch.get("user", ""))
            if not user or user in {"password", "pass", "secret"}:
                errors.append("switch.user is required (admin-style username; password stays in env)")
            port_map = switch.get("port_map")
            if not isinstance(port_map, list) or not port_map:
                errors.append("switch.port_map must list one {node, port} entry per node")
            else:
                mapped_nodes: set[str] = set()
                ports: dict[str, str] = {}
                for entry in port_map:
                    if not isinstance(entry, dict):
                        errors.append("switch.port_map entries must be {node, port} mappings")
                        continue
                    node_name = str(entry.get("node", ""))
                    port = str(entry.get("port", ""))
                    if node_name not in seen_names:
                        errors.append(f"switch.port_map references unknown node {node_name!r}")
                    mapped_nodes.add(node_name)
                    if not port:
                        errors.append(f"switch.port_map entry for {node_name!r} needs a port")
                        continue
                    if port in ports:
                        errors.append(f"switch.port_map port {port!r} is assigned twice")
                    ports[port] = node_name
                if mapped_nodes != seen_names:
                    missing = ", ".join(sorted(seen_names - mapped_nodes))
                    errors.append(f"switch.port_map must cover every node (missing: {missing})")
                for port in ports:
                    if port and port[-1] in ("a", "b") and len(port) > 2:
                        base = port[:-1]
                        for lane in ("a", "b"):
                            if base + lane not in ports:
                                errors.append(
                                    f"breakout port {port!r} needs both lanes ({base}a and {base}b)"
                                )
    elif switch is not None:
        errors.append("switch block is only valid for fabric switch")

    return errors, warnings


def _nodes(lab: dict) -> list[dict]:
    return [n for n in (lab.get("nodes") or []) if isinstance(n, dict)]


def orchestrator_of(lab: dict) -> dict:
    """Return the node mapping carrying role: orchestrator."""
    for node in _nodes(lab):
        if node.get("role") == "orchestrator":
            return node
    raise ValueError("lab has no orchestrator node")


def active_ifs(lab: dict, node: dict) -> list[str]:
    """Return the high-speed interfaces the fabric uses for this node."""
    declared = node.get("hs_ifs") or list(HS_IF_DEFAULT)
    fabric = lab.get("fabric")
    if fabric in ("pair", "ring"):
        return list(declared[:2]) or list(HS_IF_DEFAULT)
    if fabric == "switch":
        return list(declared[:1]) or [HS_IF_DEFAULT[0]]
    return []


def _link_addresses(lab: dict) -> dict[tuple[int, int], str]:
    """Map (node index, interface index) to a static ``a.b.c.d/24`` per fabric."""
    nodes = _nodes(lab)
    fabric = lab.get("fabric")
    addrs: dict[tuple[int, int], str] = {}
    for idx, node in enumerate(nodes):
        count = len(active_ifs(lab, node))
        for if_idx in range(count):
            if fabric == "pair":
                subnet = 100 + if_idx
                host = idx + 1
            elif fabric == "ring":
                # Link A (if 0): node i → node (i+1)%3, subnets 100–102.
                # Link B (if 1): node i → node (i-1)%3, subnets 103–105.
                # Six unique /24s — the documented ring scheme.
                subnet = (100 + idx) if if_idx == 0 else (103 + idx)
                host = idx + 1
            else:  # switch: one /24 per node on its active link
                subnet = 110 + idx
                host = 1
            addrs[(idx, if_idx)] = f"192.168.{subnet}.{host}/24"
    return addrs


def render_hosts_ini(lab: dict) -> str:
    """Render the generated Ansible inventory (groups derived from the orchestrator)."""
    nodes = _nodes(lab)
    orchestrator = orchestrator_of(lab)
    ansible_user = str(lab.get("ansible_user") or DEFAULT_ANSIBLE_USER)
    lines = list(GENERATED_BANNER)
    lines += [
        f"# fabric: {lab.get('fabric')} | nodes: {len(nodes)} | orchestrator: {orchestrator.get('name')}",
        "",
        "[k3s_cluster]",
    ]
    # Host lines live directly under [k3s_cluster]; per-node groups would
    # collide with the host names (Ansible "group and host with same name").
    for node in nodes:
        lines.append(
            f"{node.get('name')} ansible_host={node.get('ip')} ansible_user={ansible_user}"
        )
    lines += ["", "[k3s_server]", str(orchestrator.get("name")), "", "[k3s_agent]"]
    lines += [str(n.get("name")) for n in nodes if n is not orchestrator]
    # Ansible loads inventory/group_vars/<group>/*.yml. fabric.yml lives under
    # group_vars/generated/, so the inventory must define group `generated`.
    lines += ["", "[generated:children]", "k3s_cluster", ""]
    return "\n".join(lines)


def render_fabric_group_vars(lab: dict) -> str:
    """Render generated fabric facts consumed by the highspeed_network role."""
    nodes = _nodes(lab)
    orchestrator = orchestrator_of(lab)
    fabric = str(lab.get("fabric"))
    lines = [
        "# Purpose: generated fabric facts for Ansible roles (regenerated from inventory/lab.yaml)",
        "# Source of truth: ansible/inventory/lab.yaml",
        "# Regenerate: ./scripts/manage.sh setup or scripts/lib/topology.sh topology_render",
        "# Safety: reference facts only — workload manifests remain authoritative for NCCL env and resources",
        "",
        "# Generated — do not edit.",
        f"k3s_control_plane: \"{orchestrator.get('name')}\"",
        f"lab_fabric: \"{fabric}\"",
        f"lab_node_count: {len(nodes)}",
        f"lab_orchestrator_ip: \"{orchestrator.get('ip')}\"",
        f"lab_mgmt_subnet: \"{(lab.get('management') or {}).get('subnet')}\"",
    ]
    if fabric == "switch":
        switch = lab.get("switch") or {}
        lines += [
            f"lab_switch_host: \"{switch.get('host')}\"",
            f"lab_switch_model: \"{switch.get('model')}\"",
            f"lab_switch_user: \"{switch.get('user')}\"",
        ]
    lines += [
        "lab_highspeed_netplan_dir: \"files/generated/netplan\"",
        f"highspeed_interfaces: \"{','.join(active_ifs(lab, orchestrator))}\"",
        "",
    ]
    return "\n".join(lines)


def render_node_netplan(lab: dict, index: int) -> str:
    """Render the highspeed netplan snippet for one node (MTU 9000 on every fabric)."""
    node = _nodes(lab)[index]
    fabric = str(lab.get("fabric"))
    addrs = _link_addresses(lab)
    lines = [
        f"# Purpose: generated highspeed netplan for {node.get('name')} (fabric: {fabric})",
        "# Source of truth: ansible/inventory/lab.yaml",
        "# Regenerate: ./scripts/manage.sh setup or scripts/lib/topology.sh topology_render",
        "# Safety: highspeed interfaces only; the management LAN is never touched",
        "",
        "version: 2",
        "ethernets:",
    ]
    for if_idx, iface in enumerate(active_ifs(lab, node)):
        lines += [
            f"  {iface}:",
            "    dhcp4: false",
            "    mtu: 9000",
            "    addresses:",
            f"      - {addrs[(index, if_idx)]}",
        ]
    return "\n".join(lines) + "\n"


def _cloud_init_identity_block() -> str:
    """Render catalog groups/users for cloud-init (no authorized_keys)."""
    from lab_identities import default_catalog_path, load_catalog, render_cloud_init_users

    catalog = load_catalog(default_catalog_path())
    return render_cloud_init_users(catalog).rstrip()


def render_node_cloud_init(lab: dict, index: int) -> str:
    """Render first-boot cloud-init user-data for one node (OS/netplan/SSH prep only)."""
    node = _nodes(lab)[index]
    name = str(node.get("name"))
    fabric = str(lab.get("fabric"))
    ansible_user = str(lab.get("ansible_user") or DEFAULT_ANSIBLE_USER)
    netplan = render_node_netplan(lab, index)
    content_lines = []
    for line in netplan.splitlines():
        if line.startswith("#"):
            continue
        content_lines.append(f"      {line}" if line else "")
    write_files = ""
    if fabric != "none":
        write_files = (
            "write_files:\n"
            "  - path: /etc/netplan/99-highspeed.yaml\n"
            '    permissions: "0644"\n'
            "    content: |\n" + "\n".join(content_lines) + "\n"
        )
    runcmd = [
        "  - swapoff -a || true",
        "  - sed -i '/ swap / s/^/#/' /etc/fstab || true",
        "  - modprobe overlay || true",
        "  - modprobe br_netfilter || true",
        "  - modprobe ib_uverbs || true",
        "  - sysctl -w net.bridge.bridge-nf-call-iptables=1 || true",
        "  - sysctl -w net.bridge.bridge-nf-call-ip6tables=1 || true",
        "  - sysctl -w net.ipv4.ip_forward=1 || true",
    ]
    if fabric != "none":
        runcmd.append("  - netplan apply || true")
    runcmd += [
        "  - |",
        f"    if [ ! -f /home/{ansible_user}/.ssh/id_ed25519 ]; then",
        f'      sudo -u {ansible_user} ssh-keygen -t ed25519 -f /home/{ansible_user}/.ssh/id_ed25519 -N "" -q',
        "    fi",
        f"  - echo \"{name} ({fabric}) cloud-init prep done. Next: ansible bootstrap from the operator client.\"",
    ]
    identity_block = _cloud_init_identity_block()
    return (
        f"# Purpose: generated cloud-init user-data for {name} (fabric: {fabric}) — first-boot OS/netplan prep\n"
        "# Source of truth: ansible/inventory/lab.yaml + config/lab-identities.yaml\n"
        "# Regenerate: ./scripts/manage.sh setup or scripts/lib/topology.sh topology_render\n"
        "# Safety: OS/netplan/SSH prep only; K3s is installed later by Ansible; applying this reboots the node; no authorized_keys\n"
        "\n"
        "#cloud-config\n"
        f"hostname: {name}\n"
        "\n"
        "package_update: true\n"
        "packages:\n"
        "  - curl\n"
        "  - wget\n"
        "  - ca-certificates\n"
        "  - gnupg\n"
        "  - lsb-release\n"
        "  - jq\n"
        "  - nfs-common\n"
        "  - open-iscsi\n"
        "  - rdma-core\n"
        "  - ibverbs-utils\n"
        "  - python3-pip\n"
        "\n"
        "swap:\n"
        "  filename: /swapfile\n"
        "  size: 0\n"
        "\n"
        f"{write_files}\n"
        "runcmd:\n"
        + "\n".join(runcmd)
        + "\n"
        "\n"
        f"{identity_block}\n"
    )


def render_all(lab: dict, out_root: Path) -> list[Path]:
    """Write all generated artifacts under ``out_root/ansible``; return the paths."""
    nodes = _nodes(lab)
    written: list[Path] = []
    inventory_dir = out_root / "ansible" / "inventory"
    (inventory_dir / "group_vars" / "generated").mkdir(parents=True, exist_ok=True)
    netplan_dir = out_root / "ansible" / "files" / "generated" / "netplan"
    cloudinit_dir = out_root / "ansible" / "files" / "generated" / "cloud-init"
    netplan_dir.mkdir(parents=True, exist_ok=True)
    cloudinit_dir.mkdir(parents=True, exist_ok=True)

    hosts = inventory_dir / "hosts.ini"
    hosts.write_text(render_hosts_ini(lab), encoding="utf-8")
    written.append(hosts)
    fabric = inventory_dir / "group_vars" / "generated" / "fabric.yml"
    fabric.write_text(render_fabric_group_vars(lab), encoding="utf-8")
    written.append(fabric)
    for index, node in enumerate(nodes):
        name = str(node.get("name"))
        netplan_path = netplan_dir / f"{name}-99-highspeed.yaml"
        netplan_path.write_text(render_node_netplan(lab, index), encoding="utf-8")
        written.append(netplan_path)
        cloud_path = cloudinit_dir / f"user-data-{name}.yaml"
        cloud_path.write_text(render_node_cloud_init(lab, index), encoding="utf-8")
        written.append(cloud_path)
    return written


def lab_facts(lab: dict) -> dict:
    """Return flat key=value facts used by manage.sh and the docs config panel."""
    orchestrator = orchestrator_of(lab)
    switch = lab.get("switch") or {}
    return {
        "fabric": str(lab.get("fabric")),
        "node_count": str(len(_nodes(lab))),
        "orchestrator": str(orchestrator.get("name")),
        "orchestrator_ip": str(orchestrator.get("ip")),
        "nodes": ",".join(str(n.get("name")) for n in _nodes(lab)),
        "mgmt_subnet": str((lab.get("management") or {}).get("subnet")),
        "ansible_user": str(lab.get("ansible_user") or DEFAULT_ANSIBLE_USER),
        "bootstrap_user": str(lab.get("bootstrap_user") or DEFAULT_BOOTSTRAP_USER),
        "switch_host": str(switch.get("host", "")),
        "switch_model": str(switch.get("model", "")),
    }


def wizard_vars(lab: dict) -> dict:
    """Return pre-fill defaults for the ``manage.sh setup --interactive`` wizard."""
    nodes = _nodes(lab)
    switch = lab.get("switch") or {}
    port_map = ",".join(
        f"{entry.get('node')}:{entry.get('port')}"
        for entry in (switch.get("port_map") or [])
        if isinstance(entry, dict)
    )
    orchestrator = ""
    for node in nodes:
        if node.get("role") == "orchestrator":
            orchestrator = str(node.get("name"))
            break
    return {
        "fabric": str(lab.get("fabric", "none")),
        "mgmt_subnet": str((lab.get("management") or {}).get("subnet", "10.0.0.0/24")),
        "ansible_user": str(lab.get("ansible_user") or DEFAULT_ANSIBLE_USER),
        "bootstrap_user": str(lab.get("bootstrap_user") or DEFAULT_BOOTSTRAP_USER),
        "node_count": str(len(nodes)),
        "orchestrator": orchestrator,
        "node_names": ",".join(str(n.get("name")) for n in nodes),
        "node_ips": ",".join(str(n.get("ip")) for n in nodes),
        "switch_model": str(switch.get("model", "CRS804-4DDQ-hRM")),
        "switch_host": str(switch.get("host", "10.0.0.2")),
        "switch_user": str(switch.get("user", "admin")),
        "port_map": port_map,
    }


def main(argv: list[str] | None = None) -> int:
    """CLI entry point (validate / facts / wizard-vars / render)."""
    parser = argparse.ArgumentParser(prog="lab_topology", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("validate", "facts", "wizard-vars", "render"):
        entry = sub.add_parser(name)
        entry.add_argument("lab", help="path to the lab topology YAML")
        if name == "render":
            entry.add_argument("--out", default=".", help="root directory that will receive ansible/ artifacts")
    args = parser.parse_args(argv)

    path = Path(args.lab)
    if not path.is_file():
        print(f"lab-topology: no such file: {path}", file=sys.stderr)
        return 2
    lab = load_lab(path)
    if not lab:
        return 2
    errors, warnings = validate_lab(lab)
    if errors:
        return _fail(errors)
    for warning in warnings:
        print(f"lab-topology: warning: {warning}", file=sys.stderr)
    if args.command == "validate":
        print("lab-topology: ok")
        return 0
    if args.command == "facts":
        for key, value in lab_facts(lab).items():
            print(f"{key}={value}")
        return 0
    if args.command == "wizard-vars":
        for key, value in wizard_vars(lab).items():
            print(f"{key}={value}")
        return 0
    out_root = Path(args.out)
    written = render_all(lab, out_root)
    for item in written:
        print(f"lab-topology: wrote {item}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
