#!/usr/bin/env bash
#
# ## nvidia-dgx-spark-lab management script
#
# Simple, safe wrapper for operating heavy inference workloads on 1-4 DGX Spark nodes.
#
# SCALABLE for 1-4 DGX Spark nodes (high-speed linked for 2+).
#
# - Works with 1 node (single control-plane + worker, local multi-GPU NCCL).
# - Scales to 2-4 nodes with inter-node NCCL over dual 400G links.
# - Tailored for small clusters; for larger see notes in docs.
#
# Core safety philosophy (enforced by this script and the workloads):
#
# - Nothing starts automatically on reboot.
# - Heavy jobs use restartPolicy: OnFailure + very low backoffLimit.
# - Explicit resources.requests + limits on every container.
# - Full workloads require interactive confirmation + capacity checks.
# - Always run `stop` (or `stop-dev`) before rebooting nodes.
#
# This script (and its libs) are the primary source for the
# auto-generated Shell reference. Structured comments here power
# the nice human-readable docs under Reference → Shell Commands & Helpers.
#
# See:
#   docs/generated/shell/reference.md
#   bazelisk run //docs:docs
#
# Basic usage examples:
#   ./scripts/manage.sh status
#   ./scripts/manage.sh doctor
#   ./scripts/manage.sh start-test
#   ./scripts/manage.sh estimate kimi
#   ./scripts/manage.sh stop
#   ./scripts/manage.sh help
#
# Prefer a local kubeconfig generated by Ansible when present.

set -euo pipefail

# kcov clears BASH_SOURCE in instrumented shells — resolve paths without it.
if [[ -n "${SCRIPT_LIB_DIR:-}" && -d "${SCRIPT_LIB_DIR}" ]]; then
  SCRIPT_DIR="$(dirname "${SCRIPT_LIB_DIR}")"
elif [[ -n "${0:-}" && -f "${0}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${0}")" && pwd)"
elif [[ -n "${REPO_ROOT:-}" ]]; then
  SCRIPT_DIR="${REPO_ROOT}/scripts"
else
  SCRIPT_DIR="$(cd "$(dirname "${0:-.}")" && pwd)"
fi
# shellcheck source=lib/paths.sh disable=SC1091
source "${SCRIPT_DIR}/lib/paths.sh" 2>/dev/null || {
  lab_script_dir() {
    local depth="${1:-1}" fallback="${2:-scripts}"
    if [[ -n "${BASH_SOURCE[$depth]:-}" ]]; then
      cd "$(dirname "${BASH_SOURCE[$depth]}")" && pwd
    elif [[ -n "${0:-}" && -f "${0}" ]]; then
      cd "$(dirname "${0}")" && pwd
    elif [[ -n "${REPO_ROOT:-}" ]]; then
      echo "${REPO_ROOT}/${fallback}"
    else
      echo "${PWD}"
    fi
  }
}
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"

# Prefer local kubeconfig generated by Ansible if present
if [[ -f "${REPO_ROOT}/kubeconfig/config" ]]; then
  export KUBECONFIG="${REPO_ROOT}/kubeconfig/config"
fi

NAMESPACE="ai-inference"

# Source common modular libs. Fail fast if missing in normal use (tests ensure copies).
SCRIPT_LIB_DIR="${SCRIPT_LIB_DIR:-${SCRIPT_DIR}/lib}"
for lib in common.sh check_tool.sh domains.sh resources.sh models.sh visual.sh mcp.sh hermes.sh open-webui.sh monitoring.sh dev.sh secrets.sh sso.sh; do
  if [[ -f "${SCRIPT_LIB_DIR}/$lib" ]]; then
    # shellcheck disable=SC1090
    source "${SCRIPT_LIB_DIR}/$lib"
  else
    echo "[manage] warning: lib $lib not found (may be test env)" >&2
  fi
done

# === New automation & UX improvements ===

# ## setup / init
# Guided first-time setup helper.
# Prints recommended sequence for inventory, ansible playbooks, and first workload.
#
# @command setup
# @command init
# Usage:
#   ./scripts/manage.sh setup
#   ./scripts/manage.sh init
#
# Safety:
#   Purely informational + prints URLs. Does not modify cluster.
# @function setup
# Guided first-time setup: prints recommended Ansible and workload sequence.
# Informational only; does not modify the cluster.

setup() {
  log "=== Guided first-time setup ==="
  echo "1. Prepare ansible/inventory/hosts.ini from example (edit IPs)."
  echo "2. From workstation: ansible -i ... ping"
  echo "Typical sequence (will prompt):"
  echo "  ansible ... bootstrap-cluster.yml"
  echo "  ansible ... install-gpu-operator.yml"
  echo "  ansible ... install-dev-workspaces.yml"
  echo "  ./scripts/manage.sh start-default   # or start-test"
  print_access_info
  echo "Run individual playbooks as needed for safety."
}

# ## start-default / start-safe
# Automatically chooses a safe starting workload based on detected free GPUs.
# Falls back to the lightest test workload.
#
# @command start-default
# @command start-safe
# Usage:
#   ./scripts/manage.sh start-default
#
# Safety:
#   Calls start_test after capacity check. Never starts heavy models directly.
# @function start_default
# Auto-select safe test workload based on approximate free GPU count.
# Always delegates to start_test.

start_default() {
  require_kubectl
  check_cluster_access
  local free
  free=$(get_approx_free_gpus 2>/dev/null || echo "unknown")
  log "Free GPUs detected (approx): $free"
  if [[ "$free" != "unknown" && "$free" -lt 2 ]]; then
    warn "Low capacity; starting lightest safe workload."
  fi
  start_test
}

# ## urls / access
# Prints all important browser URLs (dashboard, Coder, Kasm, Grafana, Headlamp, etc.)
# and tips for SSH tunneling.
#
# @command urls
# @command access
# Usage:
#   ./scripts/manage.sh urls
#   ./scripts/manage.sh access
# @function urls
# Print browser URLs for dashboard, workspaces, and monitoring.

urls() {
  print_access_info
}

# ## wait
# Waits for a specific job to complete.
#
# @command wait
# Usage:
#   ./scripts/manage.sh wait <job-name>
# @function wait_for
# Wait for a named Kubernetes job to complete.
# @param $1  Job name in ai-inference namespace.

wait_for() {
  local j="${1:-}"
  if [[ -z "$j" ]]; then err "Usage: manage.sh wait <job>"; exit 1; fi
  wait_for_job "$j"
}

# @function doctor
# @command doctor
# @command preflight
# @command check
# Preflight checks: tools, cluster access, GPUs, resources, and URLs.
# Read-only; never starts or stops workloads.

doctor() {
  log "=== Lab Doctor Preflight ==="
  echo "kubectl: $(command -v kubectl && kubectl version --client --short 2>/dev/null || echo missing)"
  echo "helm: $(command -v helm && helm version --short 2>/dev/null || echo missing)"
  echo "jq: $(command -v jq && jq --version 2>/dev/null || echo missing)"
  require_kubectl && check_cluster_access && echo "Cluster: reachable"
  echo "Free GPUs (approx): $(get_approx_free_gpus 2>/dev/null || echo unknown)"
  if type print_resources_status &>/dev/null; then
    print_resources_status || true
  fi
  echo "Models registered: kimi-test kimi ray-head ray-worker nemotron-3-ultra glm-5.2 glm-5.2-rpc"
  print_access_info || true
  log "Doctor complete. Run 'setup' or specific start-* next."
}

# @function resources_cmd
# Resource Guard CLI: capacity, check, suggest, apply-policy.
resources_cmd() {
  local sub="${1:-status}"
  shift || true
  case "$sub" in
    status|""|capacity)
      print_resources_status
      ;;
    check)
      local action="${1:-}"
      local json_flag="${2:-}"
      if [[ -z "$action" ]]; then
        err "Usage: resources check <action> [--json]   e.g. model:kimi-test"
        exit 1
      fi
      if [[ "$json_flag" == "--json" ]]; then
        check_capacity "$action"
      else
        check_capacity "$action" | jq '.'
      fi
      ;;
    suggest)
      local action="${1:-}"
      if [[ -z "$action" ]]; then
        err "Usage: resources suggest <action>"
        exit 1
      fi
      suggest_free_resources "$action" | jq '.'
      ;;
    apply-policy)
      log "Applying Resource Guard manifests from k8s/base/resource-guard..."
      kubectl apply -k "${REPO_ROOT}/k8s/base/" || true
      log "Resource policy applied (PriorityClass, ResourceQuota, LimitRange, PDB)."
      ;;
    *)
      err "Unknown resources subcommand: $sub (try status, check, suggest, apply-policy)"
      exit 1
      ;;
  esac
}

# @function estimate
# @command estimate
# @command recommend
# Live resource estimator for a model profile.
# @param $1  Model name (e.g. kimi-test, kimi).

estimate() {
  local model="${1:-}"
  estimate_resources "$model"
}

# @function stop_workloads
# @command stop
# Stop all inference jobs and Ray workloads plus dev components.
# Safe to run before node reboot.

stop_workloads() {
  log "Stopping managed workloads (all models + ray)..."
  # Specific for test compatibility + labels for generality
  kubectl delete job kimi kimi-test nemotron-3-ultra glm-5.2 glm-5.2-rpc ray-head ray-worker -n "${NAMESPACE}" --ignore-not-found=true --grace-period=30 || true
  kubectl delete job -l workload=inference -n "${NAMESPACE}" --ignore-not-found=true --grace-period=30 || true
  kubectl delete job -l workload=ray -n "${NAMESPACE}" --ignore-not-found=true --grace-period=30 || true
  kubectl delete pod -l workload=inference -n "${NAMESPACE}" --ignore-not-found=true --grace-period=30 || true
  kubectl delete pod -l workload=ray -n "${NAMESPACE}" --ignore-not-found=true --grace-period=30 || true
  stop_dev_workloads || true
  log "Workloads stopped. Pods may still be terminating."
}

# @function cleanup
# @command cleanup
# Destructive namespace cleanup after interactive DELETE confirmation.
# Deletes ai-inference and dev namespace resources.

cleanup() {
  warn "This will delete ALL resources in namespace ${NAMESPACE} managed by this lab."
  read -r -p "Type 'DELETE' to confirm full cleanup: " confirm
  if [[ "$confirm" != "DELETE" ]]; then
    log "Cleanup aborted."
    exit 0
  fi

  stop_workloads
  kubectl delete svc kimi kimi-test nemotron-3-ultra glm-5.2 ray-head ray-worker -n "${NAMESPACE}" --ignore-not-found || true
  kubectl delete svc -l workload=inference -n "${NAMESPACE}" --ignore-not-found || true
  kubectl delete svc -l workload=ray -n "${NAMESPACE}" --ignore-not-found || true
  kubectl delete ns "${NAMESPACE}" --ignore-not-found || true
  # Dev ns (non-destructive on purpose; user can delete explicitly)
  for ns in coder kasm monitoring dev; do
    kubectl delete all,cm,secret,sa,role,rolebinding -n "$ns" --all --ignore-not-found || true
  done
  log "Cleanup complete."
}

# @command start-test
# Start the safe lightweight test workload (recommended first step).
# Uses lower resources (2 GPUs) for validation. Includes pre-flights.
#
# Usage:
#   ./scripts/manage.sh start-test
#   bazelisk run //:manage -- start-test
#
# Safety:
#   Lighter model. Still runs access + namespace checks. Good for first use.
#   See start-kimi for full production (after validation).
#
# @command start-kimi
# @command start-full
# Deploy the FULL heavy kimi workload (with confirmation + checks).
# Requests 8 GPUs + 128Gi+ memory. Only after start-test + start-ray on sufficient capacity.
#
# Usage:
#   ./scripts/manage.sh start-kimi
#   {{SPARK0_IP:=<your-spark0>}} ./scripts/manage.sh start-kimi
#
# Safety:
#   Requires interactive confirmation ("yes"). Pre-checks for existing kimi job and approx free GPUs.
#   Heavy: can impact host if resources exceeded. Always stop before reboot.
#
# @command start-ray
# Deploy Ray head+worker for multi-node (two-node) distributed workloads.
# Prerequisite for large models like nemotron/glm.
#
# Usage:
#   ./scripts/manage.sh start-ray
#
# Safety:
#   Starts orchestration; uses modest resources for head. Workers only on multi-node.
#   Run doctor/estimate first.
#
# @command start-nemotron
# @command start-nemotron-3-ultra
# Heavy NVFP4 Nemotron model (validate first; 2+ nodes preferred).
#
# Usage:
#   ./scripts/manage.sh start-nemotron
#
# Safety:
#   Requires confirmation + starts Ray first. Significant resources.
#   {{PLACEHOLDER}} edit as needed.
#
# @command start-glm
# @command start-glm-5.2
# Heavy GLM-5.2 1-bit UD-IQ1_M via llama.cpp RPC (validate first; 2 nodes required).
#
# Usage:
#   ./scripts/manage.sh start-glm
#
# Safety:
#   Requires confirmation. Starts spark1 RPC backend then spark0 server (no Ray).
#   Quality trade-off vs higher quants. See models-catalog.md .

case "${1:-help}" in
  status)
    ## status
    # @command status
    # Show cluster nodes, GPU resources (allocatable vs capacity), workloads,
    # recent events, dev workspaces, and convenient browser URLs.
    #
    # Usage:
    #   ./scripts/manage.sh status
    #   bazelisk run //:manage -- status
    #
    # Safety:
    #   Completely read-only. The single safest command to run at any time.
    require_kubectl
    check_cluster_access
    print_status
    print_dev_status || true
    print_access_info || true
    ;;
  start-test)
    ## start-test
    # Start the safe lightweight test workload (recommended first step).
    # Uses lower resources for validation. Includes pre-flights.
    require_kubectl
    check_cluster_access
    start_test
    ;;
  start-kimi|start-full)
    ## start-kimi
    # Start full heavy Kimi production workload (confirmation + high resources required).
    # Only after test + ray validation on sufficient capacity.
    require_kubectl
    check_cluster_access
    start_kimi
    ;;
  start-ray)
    ## start-ray
    # Deploy Ray head/worker for distributed training/inference.
    # Prerequisite for multi-node large models.
    require_kubectl
    check_cluster_access
    start_ray
    ;;
  start-nemotron|start-nemotron-3-ultra)
    ## start-nemotron-3-ultra
    # Heavy NVFP4 Nemotron model (validate first; 2+ nodes preferred).
    require_kubectl
    check_cluster_access
    start_nemotron
    ;;
  start-glm|start-glm-5.2)
    ## start-glm-5.2
    # Heavy GLM-5.2 1-bit UD-IQ1_M via llama.cpp RPC (validate first; 2 nodes required).
    require_kubectl
    check_cluster_access
    start_glm
    ;;
  start-qwen3.5-122b-nvfp4|start-qwen-122b)
    ## start-qwen3.5-122b-nvfp4
    # @command start-qwen3.5-122b-nvfp4
    # @command start-qwen-122b
    # 1-node Qwen 122B NVFP4 substitute for 397B NVFP4 frontier model.
    require_kubectl
    check_cluster_access
    start_qwen3_5_122b_nvfp4
    ;;
  start-qwen3.5-397b-spark2|start-qwen-397b-spark2)
    ## start-qwen3.5-397b-spark2
    # @command start-qwen3.5-397b-spark2
    # @command start-qwen-397b-spark2
    # 2-node Qwen 397B int4-AutoRound (vLLM TP=2 + Ray).
    require_kubectl
    check_cluster_access
    start_qwen3_5_397b_spark2
    ;;
  start-qwen3.5-397b-nvfp4|start-qwen-397b-nvfp4)
    ## start-qwen3.5-397b-nvfp4
    # @command start-qwen3.5-397b-nvfp4
    # @command start-qwen-397b-nvfp4
    # 4-node Qwen 397B NVFP4 via SGLang distributed (exact HF checkpoint).
    require_kubectl
    check_cluster_access
    start_qwen3_5_397b_nvfp4
    ;;
  start-comfy-base)
    ## start-comfy-base
    # @command start-comfy-base
    # ComfyUI base runtime with DGX Spark unified-memory patches (1 GPU, heavy).
    # First PVC install can take 10–30+ minutes. Access via port-forward :8188.
    #
    # Safety:
    #   Capacity gate + confirmation. Exclusive with other visual workloads.
    require_kubectl
    check_cluster_access
    start_comfy_base
    ;;
  stop-comfy-base)
    ## stop-comfy-base
    # @command stop-comfy-base
    # Stop ComfyUI base Deployment (retains comfy-state PVC).
    require_kubectl
    check_cluster_access
    stop_comfy_base
    ;;
  start-flux-fast)
    ## start-flux-fast
    # @command start-flux-fast
    # FLUX.2 Klein 9B NVFP4 + Nunchaku (fast image). Preflight unified mem + capacity.
    require_kubectl
    check_cluster_access
    start_flux_fast
    ;;
  start-flux-quality)
    ## start-flux-quality
    # @command start-flux-quality
    # FLUX.2 Dev FP8 (quality image). Preflight unified mem + capacity.
    require_kubectl
    check_cluster_access
    start_flux_quality
    ;;
  start-ltx-balanced)
    ## start-ltx-balanced
    # @command start-ltx-balanced
    # LTX-2.3 distilled FP8 (balanced audio-synced video).
    require_kubectl
    check_cluster_access
    start_ltx_balanced
    ;;
  start-ltx-quality)
    ## start-ltx-quality
    # @command start-ltx-quality
    # LTX-2.3 BF16 distilled (quality video).
    require_kubectl
    check_cluster_access
    start_ltx_quality
    ;;
  start-flux-to-ltx)
    ## start-flux-to-ltx
    # @command start-flux-to-ltx
    # Combined Flux Klein → LTX I2V+audio pipeline in one pod (90Gi).
    require_kubectl
    check_cluster_access
    start_flux_to_ltx
    ;;
  start-qwen36-27b|start-qwen3.6-27b)
    ## start-qwen36-27b
    # @command start-qwen36-27b
    # @command start-qwen3.6-27b
    # Exclusive Qwen3.6 27B NVFP4 dense (quality, MTP, hybrid thinking).
    require_kubectl
    check_cluster_access
    start_qwen36_27b
    ;;
  start-qwen36-35b-a3b|start-qwen3.6-35b-a3b)
    ## start-qwen36-35b-a3b
    # @command start-qwen36-35b-a3b
    # @command start-qwen3.6-35b-a3b
    # Exclusive Qwen3.6 35B-A3B NVFP4-Fast MoE (speed, flashinfer_b12x).
    require_kubectl
    check_cluster_access
    start_qwen36_35b_a3b
    ;;
  start-qwen36-dual|start-qwen3.6-dual)
    ## start-qwen36-dual
    # @command start-qwen36-dual
    # @command start-qwen3.6-dual
    # Concurrent 27B + 35B-A3B with dual overlay and GPU time-slicing.
    require_kubectl
    check_cluster_access
    start_qwen36_dual
    ;;
  stop-qwen36|stop-qwen3.6)
    ## stop-qwen36
    # @command stop-qwen36
    # @command stop-qwen3.6
    # Stop both Qwen3.6 inference Jobs.
    require_kubectl
    check_cluster_access
    stop_qwen36
    ;;
  status-qwen36|status-qwen3.6)
    ## status-qwen36
    # @command status-qwen36
    # @command status-qwen3.6
    # Show Qwen3.6 Jobs, pods, and health tips.
    require_kubectl
    check_cluster_access
    status_qwen36
    ;;
  start-coder)
    ## start-coder
    # @command start-coder
    # Deploy the Coder (self-hosted VS Code) workspace system via Helm.
    #
    # Gives you browser-based development environments on the cluster.
    # See dev-workspaces.md for details and ports.
    require_kubectl
    check_cluster_access
    start_coder
    ;;
  start-kasm)
    ## start-kasm
    # @command start-kasm
    # Deploy Kasm Workspaces (streamed desktops / apps) via Helm.
    require_kubectl
    check_cluster_access
    start_kasm
    ;;
  stop-coder)
    ## stop-coder
    # @command stop-coder
    # Stops only the Coder workspace system (helm uninstall in coder namespace).
    # Frees ~2 CPU / 4Gi for inference. Does not affect Kasm or monitoring.
    require_kubectl
    check_cluster_access
    stop_coder
    ;;
  stop-kasm)
    ## stop-kasm
    # @command stop-kasm
    # Stops only Kasm Workspaces (helm uninstall in kasm namespace).
    require_kubectl
    check_cluster_access
    stop_kasm
    ;;
  start-mcp)
    ## start-mcp
    # @command start-mcp
    # Deploy the default MCP agent toolkit (SearXNG, fetch, memory, Context7 cache proxy).
    require_kubectl
    check_cluster_access
    export LAB_NON_INTERACTIVE=1
    export LAB_CONFIRM_TOKEN="${LAB_CONFIRM_TOKEN:-yes}"
    start_mcp_stack "mcp-agent-toolkit"
    ;;
  start-mcp-full)
    ## start-mcp-full
    # @command start-mcp-full
    # Deploy full MCP toolkit with Qdrant, Firecrawl, and doc ingest (needs Nemotron embed).
    require_kubectl
    check_cluster_access
    export LAB_NON_INTERACTIVE=1
    export LAB_CONFIRM_TOKEN="${LAB_CONFIRM_TOKEN:-yes}"
    start_mcp_stack "mcp-agent-toolkit-full"
    ;;
  stop-mcp)
    ## stop-mcp
    # @command stop-mcp
    require_kubectl
    check_cluster_access
    stop_mcp_stack "all"
    ;;
  start-hermes)
    ## start-hermes
    # @command start-hermes
    # Deploy Hermes Agent (Docker) with Nemotron Omni + default MCP toolkit.
    require_kubectl
    check_cluster_access
    export LAB_NON_INTERACTIVE=1
    export LAB_CONFIRM_TOKEN="${LAB_CONFIRM_TOKEN:-yes}"
    start_hermes_stack "hermes-lab"
    ;;
  start-hermes-full)
    ## start-hermes-full
    # @command start-hermes-full
    # Deploy Hermes Agent with full MCP RAG stack (Qdrant, Firecrawl).
    require_kubectl
    check_cluster_access
    export LAB_NON_INTERACTIVE=1
    export LAB_CONFIRM_TOKEN="${LAB_CONFIRM_TOKEN:-yes}"
    start_hermes_stack "hermes-lab-full"
    ;;
  stop-hermes)
    ## stop-hermes
    # @command stop-hermes
    stop_hermes_stack
    ;;
  start-open-webui)
    ## start-open-webui
    # @command start-open-webui
    # Deploy Open WebUI (Helm) backed by Hermes gateway for agent chat.
    require_kubectl
    check_cluster_access
    export LAB_NON_INTERACTIVE=1
    export LAB_CONFIRM_TOKEN="${LAB_CONFIRM_TOKEN:-yes}"
    start_openwebui_stack "open-webui-lab"
    ;;
  stop-open-webui)
    ## stop-open-webui
    # @command stop-open-webui
    require_kubectl
    check_cluster_access
    stop_openwebui_stack
    ;;
  start-sso)
    ## start-sso
    # @command start-sso
    # Deploy Traefik v3 + cert-manager + Authelia + oauth2-proxy + IngressRoutes.
    require_kubectl
    check_cluster_access
    domains_render
    start_sso
    ;;
  stop-sso)
    ## stop-sso
    # @command stop-sso
    require_kubectl
    check_cluster_access
    stop_sso
    ;;
  sso)
    ## sso
    # @command sso
    # SSO helpers: status, ensure-secrets, ensure-tls, urls, set-password.
    shift || true
    require_kubectl
    check_cluster_access
    sso_cmd "$@"
    ;;
  domains)
    ## domains
    # @command domains
    # Domain config: show, set, render, apply (local + public hostnames).
    #
    # Usage:
    #   ./scripts/manage.sh domains show
    #   ./scripts/manage.sh domains set --local lab.local
    #   ./scripts/manage.sh domains render
    #   ./scripts/manage.sh domains apply
    shift || true
    domains_cmd "$@"
    ;;
  monitoring)
    ## monitoring
    # @command monitoring
    # Observability subcommands: status | verify (Prometheus scrape health).
    shift || true
    require_kubectl
    check_cluster_access
    case "${1:-status}" in
      status)
        get_monitoring_status_json | python3 -m json.tool
        ;;
      verify)
        verify_scrape_targets | python3 -m json.tool
        ;;
      *)
        echo "Usage: ./scripts/manage.sh monitoring status|verify"
        exit 1
        ;;
    esac
    ;;
  start-monitoring|start-dashboard)
    ## start-monitoring
    # @command start-monitoring
    # @command start-dashboard
    # Deploy the full observability + dashboard stack:
    #   - node-exporter, kube-state-metrics, blackbox-exporter, Prometheus
    #   - Grafana (provisioned dashboards + Prometheus datasource)
    #   - Headlamp (K8s UI) + custom lab dashboard (Next.js)
    # When SSO_ENABLED=1, also starts the Traefik + Authelia stack first.
    #
    # Usage:
    #   ./scripts/manage.sh start-monitoring
    #   ./scripts/manage.sh urls   # to see the addresses
    require_kubectl
    check_cluster_access
    if sso_enabled; then
      start_sso
    fi
    start_monitoring
    ;;
  setup|init)
    ## setup
    # @command setup
    # @command init
    # Guided first-time setup. Prints steps for inventory, ansible, and first workload.
    # See function definition above for details.
    setup
    ;;
  start-default|start-safe)
    ## start-default
    # @command start-default
    # @command start-safe
    # Auto-selects safe test workload based on free GPUs.
    start_default
    ;;
  urls|access)
    ## urls
    # @command urls
    # @command access
    # Prints all dashboard / workspace / monitoring URLs.
    urls
    ;;
  wait)
    shift
    ## wait
    # @command wait
    # Waits for a named job to reach completion.
    wait_for "$@"
    ;;
  doctor|preflight|check)
    ## doctor
    # @command doctor
    # @command preflight
    # @command check
    # Comprehensive pre-flight checks.
    #
    # Verifies:
    # - Required tools (kubectl, helm, jq, etc.)
    # - Cluster reachability and node labels (highspeed, role)
    # - Approximate free GPUs across the cluster
    # - Current workloads in the ai-inference namespace
    # - Prints handy URLs for dashboard / Coder / Grafana etc.
    #
    # Usage:
    #   ./scripts/manage.sh doctor
    #   bazelisk run //:manage -- doctor
    #
    # Safety:
    #   Read-only. Never starts or stops anything.
    #   Run this before *every* heavy workload.
    require_kubectl || true
    check_cluster_access || true
    doctor
    ;;
  resources|capacity)
    ## resources
    # @command resources
    # @command capacity
    # Resource Guard: cluster capacity, pre-flight checks, free-resource suggestions.
    #
    # Usage:
    #   ./scripts/manage.sh resources
    #   ./scripts/manage.sh resources check model:kimi --json
    #   ./scripts/manage.sh resources suggest model:kimi
    #   ./scripts/manage.sh resources apply-policy
    #
    # Safety:
    #   Read-only except apply-policy (installs guardrail manifests).
    shift || true
    require_kubectl
    check_cluster_access
    resources_cmd "$@"
    ;;
  estimate|recommend)
    ## estimate
    # @command estimate
    # @command recommend
    # Live resource estimator + recommended next command for a model.
    #
    # Uses current cluster capacity (free GPUs) + known model profiles
    # (from models.sh) to tell you whether a workload is likely safe.
    #
    # Supports {{PLACEHOLDER}} substitution via the interactive docs panel
    # so copied commands are already filled in with your cluster values.
    #
    # Usage:
    #   ./scripts/manage.sh estimate kimi-test
    #   ./scripts/manage.sh estimate kimi
    #
    # Safety:
    #   Does not start anything. Only reads allocatable resources.
    shift
    require_kubectl || true
    check_cluster_access || true
    estimate "$@"
    ;;
  stop-dev)
    ## stop-dev
    # @command stop-dev
    # Stops only dev workspaces (Coder, Kasm, dashboard/monitoring stack).
    # Leaves inference workloads running.
    require_kubectl
    check_cluster_access
    stop_dev_workloads
    ;;
  stop)
    ## stop
    # @command stop
    # Stops all inference jobs (models + ray) + dev workloads.
    # Safe command to run before any reboot.
    require_kubectl
    check_cluster_access
    stop_workloads
    ;;
  cleanup)
    ## cleanup
    # @command cleanup
    # **Destructive**: deletes the ai-inference namespace and dev namespaces.
    # Requires interactive "DELETE" confirmation.
    # Use with extreme caution.
    require_kubectl
    check_cluster_access
    cleanup
    ;;
  secrets)
    ## secrets
    # @command secrets
    # Dashboard secrets vault: master key lifecycle and metadata status (never prints values).
    #
    # Usage:
    #   ./scripts/manage.sh secrets status
    #   ./scripts/manage.sh secrets ensure-key
    #   ./scripts/manage.sh secrets list
    #
    # Safety:
    #   Read-only except ensure-key (idempotent K8s Secret create).
    shift || true
    require_kubectl
    check_cluster_access
    secrets_cmd "$@"
    ;;
  help|--help|-h)
    cat <<EOF
nvidia-dgx-spark-lab manage.sh

Commands:
  status         Show nodes, GPU resources, and current workloads
  start-test     Deploy the lighter kimi-test workload (safer)
  start-kimi     Deploy the FULL heavy kimi workload (with confirmation + checks)
  start-ray      Deploy Ray head+worker for multi-node (two-node)
  start-nemotron Deploy Nemotron 3 Ultra (with Ray, safety checks)
  start-glm      Deploy GLM-5.2 (with Ray, safety checks)
  start-comfy-base  Deploy ComfyUI base (visual; Spark unified-memory patches)
  stop-comfy-base   Stop ComfyUI base Deployment (PVC retained)
  start-flux-fast   FLUX.2 Klein 9B NVFP4+Nunchaku (fast)
  start-flux-quality FLUX.2 Dev FP8 (quality)
  start-ltx-balanced LTX-2.3 distilled FP8 (balanced video)
  start-ltx-quality  LTX-2.3 BF16 distilled (quality video)
  start-flux-to-ltx  Flux→LTX T2I→I2V+audio pipeline (90Gi)
  start-coder    Deploy Coder (VS Code workspaces) via Helm
  start-kasm     Deploy Kasm Workspaces via Helm
  start-mcp      Deploy MCP agent toolkit (default stack)
  start-mcp-full Deploy MCP toolkit + Qdrant/Firecrawl/doc ingest
  stop-mcp       Stop all MCP agent-tools workloads
  start-hermes   Deploy Hermes Agent (Docker, gateway + dashboard)
  start-hermes-full Deploy Hermes + full MCP RAG integration
  stop-hermes    Stop Hermes Agent container and inference port-forward
  start-open-webui Deploy Open WebUI chat UI (Hermes gateway backend)
  stop-open-webui  Stop Open WebUI Helm release and Hermes gateway bridge
  stop-coder     Stop Coder only (frees dev resources)
  stop-kasm      Stop Kasm only (frees dev resources)
  start-sso       Deploy Traefik + Authelia SSO stack (cert-manager, routes)
  stop-sso        Stop SSO stack (Traefik, Authelia, cert-manager)
  sso             SSO helpers: status, ensure-secrets, ensure-tls, urls
  domains         Domain config: show, set, render, apply (local + public hostnames)
  start-monitoring Deploy Prometheus + exporters + Grafana (provisioned) + Headlamp + lab dashboard (+ SSO if SSO_ENABLED=1)
  monitoring       Observability subcommands: status | verify
  start-default  (or start-safe) Auto choose safe test workload based on free GPUs
  setup|init     Guided first-time setup prompts (bootstrap + gpu + dev)
  urls|access    Print browser URLs for dashboard/Coder/etc + optional pf
  wait <job>     Wait for a job to complete
  doctor|check   Preflight checks (tools, cluster, GPUs, access)
  resources      Resource Guard capacity / check / suggest / apply-policy
  estimate <model>   Full resource estimator (free GPUs + profile + editable command)
  stop-dev       Stop dev workspaces & dashboard components
  stop           Stop all jobs (kimi, test, new models, ray) + dev
  cleanup        Delete namespace and all managed resources (destructive)
  secrets        Secrets vault status / ensure master key / list names (no values)
  help           This message

Environment:
  KUBECONFIG is automatically set if ./kubeconfig/config exists.

Safety notes:
  - Full workloads use restartPolicy: OnFailure with very low backoffLimit.
  - Nothing starts automatically on reboot.
  - Always run 'stop' before rebooting nodes.
EOF
    ;;
  *)
    err "Unknown command: $1"
    echo "Run './scripts/manage.sh help' for usage."
    exit 1
    ;;
esac
